---
driver:
  name: vagrant

provisioner:
    name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    provisioner:
        nodes_path: "test/integration/nodes"
        environments_path: "test/integration/environments"
        client_rb:
            environment: "kitchentest"
    driver:
      vm_hostname: ecflow.met.test
    run_list:
        - recipe[apt]
        - recipe[ecflow::default]
    attributes: {
        "ecflow": {
            "install_testsuite": false
        }
    }
